name: 'Version Number Detector'
description: 'creates a version number that can be used in subsequent steps based on release/tag/branch/commit'
outputs:
  version-number:
    description: 'determined version number'
    value: ${{steps.logic.outputs.result}}
runs:
  using: "composite"
  steps:
    - name: determine version number
      id: logic
      env:
        GITHUB_RELEASE_TAG: ${{ github.event.release.tag_name }}
      run: |
        if [ -n "$GITHUB_RELEASE_TAG" ]; then
          echo "detected RELEASE = $GITHUB_RELEASE_TAG"
          echo "result = $GITHUB_RELEASE_TAG"
          echo "result=$GITHUB_RELEASE_TAG" >> "${GITHUB_OUTPUT}"
        else
          branch=local
          hash=`date +%Y-%m-%d_%H-%M-%S`
          if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
            branch="$(echo "$GITHUB_REF" | cut -c 12- | tr '/' '-')"
            echo "detected branch = $branch"
          else
            echo "don't know how to handle GITHUB_REF=$GITHUB_REF"
          fi
        
          if [ -n "$GITHUB_SHA" ] && [ "${#GITHUB_SHA}" -eq "40" ]; then
            hash="${GITHUB_SHA:0:7}"
            echo "detected hash = $branch"
        
            echo "result = $branch-$hash"
            echo "result=$branch-$hash" >> "${GITHUB_OUTPUT}"
          else
            echo "GITHUB_SHA is not 40chars long: $GITHUB_SHA"
          fi
        
        fi
      shell: bash
